<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net462</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>PlayniteAccountManager</AssemblyName>
    <RootNamespace>PlayniteAccountManager</RootNamespace>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PlayniteSDK" Version="6.17.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Security" />
    <Reference Include="System.Management" />
    <Reference Include="System.Web.Extensions" />
    <None Include="extension.yaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
